---
- name: user
  hosts: demo
  vars_files:
    - ./my_vars.yml
  tasks:
    - name: Preconfig block
      block: 
        - name: Create user
          user:
            name: "{{ user }}"
            state: present
          register: error
        - name: Install curl
          apt:
            name: curl
            update-cache: yes
          register: error
      become: true
      when: ansible_facts['distribution'] == 'Ubuntu'
      rescue:
        - name: Some error print
          debug:
            var: error
      always:
        - name: Reboot
          debug:
            msg: Reboot...